# Application settings
spring:
  application:
    name: backend
      # SMTP Server Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: pixelwave.cb@gmail.com
    password: dfhzvhjjxnbdixjg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JPA and Hibernate settings


# Datasource settings
  datasource:
    url: jdbc:mysql://localhost:3306/store_db  # Database connection URL
    username: root  # Database username
    password:  # Database password
    driver-class-name: com.mysql.cj.jdbc.Driver  # Driver class for MySQL
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  # SQL initialization settings
  sql:
    init:
      mode: always  # SQL initialization mode: always (execute scripts on every startup), never (do not execute scripts on startup)
      schema-locations:
        - classpath:test-data.sql

# Server settings
server:
  error:
    include-message: always  # Include error message in the server response for debugging purposes
